CREATE TABLE ids(
   lid BIGINT GENERATED ALWAYS AS IDENTITY, 
   model VARCHAR(255), 
   id VARCHAR(255), 
   is_uid SMALLINT
)

CREATE PROCEDURE getlid ( IN model VARCHAR(255), IN id VARCHAR(255), IN is_uid SMALLINT )
PARAMETER STYLE JAVA
LANGUAGE JAVA 
READS SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.getLID'

CREATE PROCEDURE createlid ( IN model VARCHAR(255), IN id VARCHAR(255), IN is_uid SMALLINT )
PARAMETER STYLE JAVA
LANGUAGE JAVA 
MODIFIES SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.createLID'

CREATE PROCEDURE getid ( IN lid BIGINT )
PARAMETER STYLE JAVA
LANGUAGE JAVA 
READS SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.getID'