CREATE TABLE bids(
   lid BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 2),
   model VARCHAR(255), 
   id VARCHAR(255)
)

CREATE TABLE uids(
   lid BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 2, INCREMENT BY 2),
   id VARCHAR(255)
)

CREATE INDEX bids_lid ON bids(lid)

CREATE INDEX bids_id ON bids(model, id)

CREATE INDEX uids_lid ON uids(lid)

CREATE INDEX uids_id ON uids(id)

CREATE PROCEDURE getlid ( IN model VARCHAR(255), IN id VARCHAR(255))
PARAMETER STYLE JAVA
LANGUAGE JAVA 
READS SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.getLID'

CREATE PROCEDURE createlid ( IN model VARCHAR(255), IN id VARCHAR(255) )
PARAMETER STYLE JAVA
LANGUAGE JAVA 
MODIFIES SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.createLID'

CREATE PROCEDURE getid ( IN lid BIGINT )
PARAMETER STYLE JAVA
LANGUAGE JAVA 
READS SQL DATA
DYNAMIC RESULT SETS 1
EXTERNAL NAME 'com.mysema.rdfbean.object.identity.DerbyProcedures.getID'
